protifolio-module1
beteland123/prortifolio pull request #2
Opened 2023-03-25 09:42 UTC by beteland123

Added a mobile-responsive nature to the website
Added CSS  to style 
Configured the linter successfully

2023-03-25 10:00 UTC, Shedrack-Sunday requested changes
Hi @beteland123 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that has failing linters. Please change the version of the lighthouse linters on the `linter.yml` file to version `12` to fix the issue 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-25 10:37 UTC, divinecharlotte commented on index.html
> +    <div class="background"><img src="img/header-shapes mobile.png" class="image"></div>
- [ ] kindly consider adding this image as a background image in your CSS for aesthetic reasons

2023-03-25 10:46 UTC, divinecharlotte commented on index.html
> +    <section class="headline">
- [ ] kindly consider making sure that the content of this section are aligned with flexbox.

* This gives us a lot of options to align all our elements, plus, it's responsive.

2023-03-25 16:19 UTC, MeqdamAlqudah reviewed
Hi @beteland123 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that have linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-25 17:54 UTC, mahbubul14 requested changes
**Hi @beteland123,**

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-25 17:54 UTC, mahbubul14 commented on index.html
> +    </section>
- [ ] As the previous reviewer suggested, kindly try to match your design to the Figma design. The section has the margins (top, bottom, left, right) defined in the design. The section uses the font and colors (background and font) defined for the template. Kindly follow the original vision, if it's pretty and works, it will be a wonderful website. :+1: 

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![yourdesign](https://user-images.githubusercontent.com/70483835/227733475-add9e969-c0d6-472b-983d-83b689470b09.png) | ![figma](https://user-images.githubusercontent.com/70483835/227733473-986bdd6b-d5b2-4a25-b985-9096f46d8db8.png)

2023-03-27 16:23 UTC, divinecharlotte requested changes
Hi @beteland123  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive commit messages ✔️ 
- clean code ✔️ 
- Descriptive PR ✔️ 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 16:23 UTC, divinecharlotte commented on index.html
> +                        <a href="https://www.linkedin.com/in/betel-andarge-1b9446223"><img src="img/Vector (5).png"></a>
- [ ] kindly consider adding the right path to this icon to make it visible on the page and this will make your UI more professional and interactive

2023-03-27 16:23 UTC, divinecharlotte commented on style.css
> +    height: 9.375em;
- [ ] kindly consider decreasing this height in order to have an exact copy of the provided design check the images below 
- your design 👇 
![fs](https://user-images.githubusercontent.com/60146030/228000245-c853f19e-8086-4f70-a4c4-c22604b94ed5.PNG)


- provided design 👇 
![hh](https://user-images.githubusercontent.com/60146030/228000752-10c9277b-d280-4d39-b179-7db8e5d23a74.PNG)

2023-03-27 16:23 UTC, divinecharlotte commented on style.css
> +  }
- [ ] kindly consider giving this headline background a bottom border-left-radius to match the provided design

2023-03-27 18:59 UTC, beteland123 commented on index.html
> +                        <a href="https://www.linkedin.com/in/betel-andarge-1b9446223"><img src="img/Vector (5).png"></a>
I don't understand it is the right path, it goes to the LinkedIn page.

2023-03-27 20:49 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @beteland123 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 20:49 UTC, tresorsawasawa commented on index.html
> +                        <a href="https://www.linkedin.com/in/betel-andarge-1b9446223"><img src="img/Vector (5).png"></a>
- [ ] As mentioned by the previous reviewer to use the right path, he was referring about the broken image of the linkedin icon. I noticed that you use the Linkedin icon as two images and that causes your styling issue. I suggest you download it as one image then style it correctly to match the Figma design. If you don't know ow to download it as one image, check you can check your slack to find the whole image or you can even use **[Font Awesomes icons](https://fontawesome.com/icons)** instead of images.
**Also remember to increase the spacing at the left of your social media icons**
![Screenshot from 2023-03-27 16-46-38](https://user-images.githubusercontent.com/83042742/228063192-1eec0d1e-f655-46c7-b30e-8f3bd9f5a24f.png)

2023-03-27 20:49 UTC, tresorsawasawa commented on index.html
> +           <a href="https://img.freepik.com/free-vector/creative-gradient-code-logo_23-2148820572.jpg?w=740&t=st=1679754948~exp=1679755548~hmac=0c558f4c834b90047b09f02528084de9fa31f91b87758d3a182d7b6
- [ **OPTIONAL** ] **RECOMMENDED:** I think it would be better if you update your `Logo` text styling by removing the underline decoration styling to match your Figma chosen design. **I recommend you fix this as it was not mentioned by the previous reviewer.**

2023-03-28 00:33 UTC, jerryowusu requested changes
Hi @beteland123 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost there2](https://user-images.githubusercontent.com/65233860/228096516-5e4853dc-042b-4858-954d-e60f79bf9e47.gif)


 ## Highlights
Great effort so far :heavy_check_mark: 
No linter errors :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 00:33 UTC, jerryowusu commented on index.html
> +                        </a>
As requested by the previous reviewer, kindly fix the image/icon for the linkedin link since it is still broken and not showing. This is because you are referring `Linkedin icon.png"` which is not available in your project image (img) directory. Kindly make sure the image is available or you are making the right reference just like all the other social media icons. 

![Screenshot from 2023-03-28 00-21-58](https://user-images.githubusercontent.com/65233860/228095848-c069eb2c-83de-4bba-a1f3-596b5d1313b1.png)

2023-03-28 00:33 UTC, jerryowusu commented on index.html
> +</html>
[OPTIONAL]  Kindly consider using a code formatter like prettier to make your code more clean, readable, and easy to understand :+1:

2023-03-28 09:01 UTC, wayungi approved these changes
Hi @beteland123 , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] All linter checks passing ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Project up and running ✔️ 
- [ ] All requested changes implemented

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 12:06 UTC, merged