Finish portifoio  :module1
beteland123/prortifolio pull request #4
Opened 2023-03-26 04:59 UTC by beteland123

1. Added the work section to the website
2. Added the comment section
3. Addded the grid property

2023-03-28 17:14 UTC, Olamarx requested changes
Hi @beteland123,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has git conflict and cannot verify the linters, kindly fix it up.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-29 00:45 UTC, Shedrack-Sunday requested changes
Hi @beteland123       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights:
✔️ good code structure
✔️ good PR summary
✔️ Nice UI
  
# Required Changes ♻️

- [x] I must admit you have really put in the effort so far in this project, however, the changes required below need to be implemented :
- A few semantic issues and style adjustments are needed👏


_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-29 00:45 UTC, Shedrack-Sunday commented on index.html
> +                </h1>
- [ ] The `h1` tag is the most important heading element in HTML and represents the main heading of a page or section. Having multiple `h1` tags can cause confusion in search engine optimization (SEO) and accessibility, as well as make it difficult for screen readers to understand the main content of the page. 
- Since you have it already above in your intro, It is recommended to use only one `h1` tag per page and use other heading tags (h2, h3, etc.) to create a clear and structured document outline.
- [ ] **Kindly Implement these changes on all cards below**

2023-03-29 00:45 UTC, Shedrack-Sunday commented on index.html
> +                    </div>
- [ ] Using a heading tag instead of a paragraph tag for a header is more semantically correct because it conveys the importance and hierarchy of the content. By using a heading tag, you are telling the browser and search engines that the content is important and should be considered a heading or a subheading. This can help improve the accessibility, SEO, and overall usability of your website.
- [ ] These sections are clearly for `hx` tags, and not `p` tags 👍 
- [ ] **Kindly Implement these changes on all cards below**

2023-03-29 00:45 UTC, Shedrack-Sunday commented on index.html
> +        <h1 class="prim-text">About my self</h1>
- [ ] Please refer to my detailed review on the use of only one `h1` tag i a project in line `61` above 👍

2023-03-29 00:45 UTC, Shedrack-Sunday commented on index.html
> +        </div>
- [ ] Kindly refer to my detailed comment on the use of `hx` for headers in line `62`, as this is not a paragraph 👍

2023-03-29 00:45 UTC, Shedrack-Sunday commented on index.html
> +            </div>
- [ ] Kindly adjust the width of the `see project` button, as it's a little stretched compared to what's given on the figma design. This will give a better user appeal and experience in general 👍 
- **Do this for all buttons**

## Your view :
![image](https://user-images.githubusercontent.com/50990925/228396825-02fad738-23ff-460c-a471-76b186860f1d.png)

## Figma:
![image](https://user-images.githubusercontent.com/50990925/228396858-9c24f7cb-8d03-45dd-ba6a-b9fabc256c32.png)

2023-03-29 00:45 UTC, Shedrack-Sunday commented on index.html
> +            <li class="vic"> <a href=""><img src="img/Vector (4).png"></a></li>
- [ ] In reference to the figma design, Kindly add spacing to the social links as done on the design. This gives user a more visually appealing view 👍 

## View:
![image](https://user-images.githubusercontent.com/50990925/228397208-0423bb01-501e-42bc-920a-e46a3a328493.png)

## Figma:
![image](https://user-images.githubusercontent.com/50990925/228397232-04de24e7-7a28-4e43-b545-f9ec5065e476.png)

2023-03-29 00:45 UTC, Shedrack-Sunday commented on index.html
> +            </div>
- [ ] The horizontal lines you implemented are impressive, 👏 . However, kindly dime it to have the same visual view that suites the overall color texture of the card

## View:
![image](https://user-images.githubusercontent.com/50990925/228397582-f3fe40ed-97f0-4184-a18e-15090066be7f.png)

## Figma:
![image](https://user-images.githubusercontent.com/50990925/228397620-83f86002-1d76-4359-8a48-304b14909ce7.png)

2023-03-29 18:06 UTC, Lizdev-05 approved these changes
Hi @beteland123, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- ✔️ good code structure
- ✔️ good PR summary
- ✔️ Nice UI

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 18:09 UTC, merged